name: Build Multi-Platform Application

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload Windows Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'Shuiyuan Exporter'
        options: --onefile --name "Shuiyuan Exporter"

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload MacOS Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'Shuiyuan Exporter'
        options: --onefile --name "Shuiyuan Exporter"

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Upload Linux Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.12'
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'Shuiyuan Exporter'
        options: --onefile --name "Shuiyuan Exporter"
